# ================================
# 1. Build del frontend
# ================================
FROM node:20 AS build

WORKDIR /app

COPY package.json package-lock.json ./

# ---- FIX para Rollup en Docker (este es el que lo arregla) ----
RUN npm_config_ignore_optional=false npm install --force
RUN npm rebuild rollup esbuild --platform=linux --arch=x64

# Instalar dependencias normales
RUN npm install --legacy-peer-deps

# Copiar resto del proyecto
COPY . .

# Build de producción
RUN npm run build


# ================================
# 2. Servidor Nginx
# ================================
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist ./
COPY public/config.json ./config.json
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
