worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        # Evitar cache del config.json
        location /config.json {
            add_header Cache-Control "no-cache, must-revalidate";
        }

        # Soporte para React Router
        try_files $uri /index.html;
    }
}
