spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  sql:
    init:
      mode: always
      continue-on-error: true


  application:
    name: hotel_API
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/auth/google/callback"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-time: ${JWT_EXPIRATION}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}


admin:
  fullName: ${ADMIN_FULLNAME}
  country: ${ADMIN_COUNTRY}
  documentNumber: ${ADMIN_DOCUMENT}
  phoneNumber: ${ADMIN_PHONE}
  email: ${ADMIN_EMAIL}
  userName: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

enterprise:
  name: ${ENTERPRISE_NAME}
  address: ${ENTERPRISE_ADDRESS}
  phone_number: ${ENTERPRISE_PHONE}
  lineBusiness: ${ENTERPRISE_LINE}
  nit: ${ENTERPRISE_NIT}
  email: ${ENTERPRISE_EMAIL}


